# Scoring weights configuration for part prioritization

# Base feature weights (must sum to 1.0)
base_weights:
  demand_score: 0.35           # Increased from 0.25 - Historical demand importance
  availability_score: 0.35     # Increased from 0.25 - Stock and leadtime importance  
  inv_leadtime_weeks: 0.15     # Delivery speed importance
  inv_moq: 0.10               # Order flexibility (kept as it's about order constraints, not pricing)
  is_authorized: 0.05         # Source reliability

# Alternative weight sets for A/B testing
weight_variants:
  demand_focused:
    demand_score: 0.50
    availability_score: 0.25
    inv_leadtime_weeks: 0.15
    inv_moq: 0.05
    is_authorized: 0.05
    
  availability_focused:
    demand_score: 0.20
    availability_score: 0.50
    inv_leadtime_weeks: 0.20
    inv_moq: 0.05
    is_authorized: 0.05

# Business rule boosts - multiplicative improvements (unchanged)
business_boosts:
  ample_stock:
    condition: "inventory >= 10 * moq"
    multiplier: 1.1
    description: "High inventory relative to MOQ"
    
  immediate_ship:
    condition: "leadtime_weeks == 0"
    multiplier: 1.15
    description: "Zero lead time for immediate shipping"
    
  authorized_source:
    condition: "source_type == 'Authorized'"
    multiplier: 1.05
    description: "Component from authorized distributor"
    
  high_demand:
    condition: "demand_all_time > 100"
    multiplier: 1.08
    description: "Popular component with high historical demand"